import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Navbar/Navbar";
import { ThemeProvider } from "next-themes";
import { Footer } from "./_footer/page";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CPT",
  description: "Generated by create next app",
  icons: {
    icon: "/image 175.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden antialiased screen-image bg-background top-shadow-overlay`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <Navbar></Navbar>
          <Suspense fallback={<Loading></Loading>}>
            <main className="w-full overflow-x-hidden no-scrollbar h-full">
              {children}
            </main>
          </Suspense>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
